### ISSUE TITLE
How to configure

### ISSUE THREAD

**Issue by ingvijonasson** [vue-a11y/vue-axe#1]
Thank you for maintaining this plugin.
I somehow can not find out how to work with the axe-core and customize my needs. 

Inspecting the [demo](https://vue-axe.surge.sh/) where I see a color contrast error in the console.

<img width="569" alt="screen shot 2018-09-06 at 7 40 55 pm" src="https://user-images.githubusercontent.com/655618/45175086-d5231d00-b20c-11e8-8ec2-fb912b5dd8aa.png">

I am trying to reproduce it myself but without any success.
I think this is turned on by default but I tried to configure like this anyway:

```
config: {
    rules: [
        { id: "color-contrast", enabled: true },
        ...
     ]
}
```

Any ideas or tips on how I can possibly enable this. Any help or tips very much appreciated!

BTW. I did test my app with axe-coconut where I get multiple error instance on color contrast so I am sure that these issues do exists

**Comment by ktquez** [comment]
@ingvijonasson 
Did you solve it?
The plugin has undergone an update, could you test with the most current version and see if it still persists with your doubt?
