### ISSUE TITLE
Eslint plugin

### ISSUE THREAD

**Issue by AndreGCRamos** [vue-a11y/vue-axe#10]
This is not directly related with this project, but is there any plan of extend your accessibility stack onto linting? There is this [eslint plugin](https://github.com/maranran/eslint-plugin-vue-a11y) based on the jsx-a11y project, but is poorly maintained and has quite a few flaws.

There are several advantages into doing it this way and I feel, if applied in HMR, it will help developers to create more accessible UI's.

Is there any way you could add a properly funcioning and maintained eslint plugin to your projects? I'd happily give a hand ;)

**Comment by ktquez** [comment]
@AndreGCRamos 
It's a good idea, we'll get in touch with him and see if the maintainer wants to be part of the team and bring the eslint a11y plugin to our repositories and have more people to maintain and update it.

**Comment by ktquez** [comment]
@AndreGCRamos 

@kddeisz created an eslint plugin that corrects and adds some rules and is being maintained by the vue-a11y project.

Take a look: https://github.com/vue-a11y/eslint-plugin-vuejs-accessibility
