### ISSUE TITLE
Feature request: Delay until loaded

### ISSUE THREAD

**Issue by rudolfbyker** [vue-a11y/vue-axe#22]
My app has a loading animation outside of the element in which Vue is mounted:

```html
<body>
  <div id="loading" role="progressbar">
    <img src="<%= BASE_URL %>animation.gif" alt="" />
    <div>Loading…</div>
  </div>
  <div id="app" aria-busy="true"></div>
</body>
```

One Vue is mounted and everything is loaded, the animation fades out and is removed from the DOM:

```html
<body>
  <div id="app">
    <!--- Vue SPA is mounted here, and provides the <main> tag. --->
  </div>
</body>
```

I would like to delay running VueAxe until the loading is completed. I.e. I would like to start it manually, or delay it until a certain event fires, because VueAxe is complaining about a few things like missing <main> tag, etc. while loading.

**Comment by ktquez** [comment]
Hi @rudolfbyker, how are you?

A great idea, I'll put it on the vue-axe v3 checklist.

Thank you for that.

**Comment by rudolfbyker** [comment]
Hi there, and thanks for you consideration.

**Comment by ktquez** [comment]
@rudolfbyker 

Now available in this [v1.2.0](https://github.com/vue-a11y/vue-axe#configuration).
We added the delay and also a way to [execute it manually](https://github.com/vue-a11y/vue-axe#run-axe-manually).

Thanks for the suggestion.

**Comment by rudolfbyker** [comment]
Thanks, it's great that I can now run it manually, but how do I disable the automatic run when I do that?

**Comment by ktquez** [comment]
@rudolfbyker 

I even thought of inserting a `skip` or `auto`, but I didn't add it.

At the moment you can, when manually executing, clear the console, through the `clearConsole` property.

Soon, I will add a property to disable automatic mode.

Thank you for that
