### ISSUE TITLE
Feature request: Make styles customizable

### ISSUE THREAD

**Issue by rudolfbyker** [vue-a11y/vue-axe#23]
The defaults for `export const STYLE` in `constants.js` are not very pretty, even for DX. I would like to modify it if possible. Until then, I'm using a patched version of vue-axe. ;)

**Comment by ktquez** [comment]
I will add this customization in v3 too.
Thank you for that.

**Comment by ktquez** [comment]
@rudolfbyker 

Now available in this [v1.2.0](https://github.com/vue-a11y/vue-axe#configuration), could you test it?
Thanks for the suggestion.
