### ISSUE TITLE
Console cleared even when `clearConsoleOnUpdate: false`

### ISSUE THREAD

**Issue by rudolfbyker** [vue-a11y/vue-axe#26]
I can't find a way to disable all console clears from this module. It's quite important for my development process that the console is NEVER cleared.

**Comment by ktquez** [comment]
Again, thanks for the contributions when using the vue-axe and reporting some improvements. 
I released a [v2.1.0](https://github.com/vue-a11y/vue-axe/tree/v2.1.0) version right now.

- I added the option `auto` to be able to disable the automatic verification (default: true);

```javascript
Vue.use(VueAxe, { auto: false }) // Disables automatic verification
```

- Now, when executing the `$axe.run` method, the` clearConsole` property by default will get the same value as the `clearConsoleOnUpdate` option (default: false);

```javascript
// not clear console
this.$axe.run() 
```

```javascript
// using clear console
this.$axe.run({ clearConsole: true }) 
```

**Comment by rudolfbyker** [comment]
It's working well now! Thanks!

**Comment by ktquez** [comment]
I thank you.
