### ISSUE TITLE
Last notification is being cleared every update

### ISSUE THREAD

**Issue by MechJosh0** [vue-a11y/vue-axe#27]
[A commit from 12 days ago](https://github.com/vue-a11y/vue-axe/blame/master/src/index.js#L47) is clearing the `lastNotification` value and making `vue-axe` output the same previous notification each time there is an update.

This is causing pointless duplicated debug per Vue update. It should only be outputting Axe information when there is a change of errors, rather than each time there is a change in HTML.

**Comment by ktquez** [comment]
Hi @MechJosh0 

This is because `clearConsoleOnUpdate`  has become `false` by default.

But I think this resolves by setting it to `true` at installation

```
Vue.use(VueAxe, {
  clearConsoleOnUpdate: true
})
```

**Comment by MechJosh0** [comment]
Thanks for the quick response.

Perhaps I'm not being clear. I've created an example repo here https://codesandbox.io/s/strange-sunset-e70dy?file=/src/main.js

If you click `Plus +1` it'll add `1` to the number value. When you reach `5` it'll display `HIGH NUMBER` warning text, this text breaks a11y rules due to being too white on white background.

When `clearConsoleOnUpdate === false`, clicking `Plus +1` will output a console debug `Plus 1`. Once it reaches an a11y issue, it'll output the a11y error message.

![image](https://user-images.githubusercontent.com/11144798/82885782-81ef8180-9f3d-11ea-93c8-6b9310c90d6b.png)

So far this is all as expected. But continuing to press `Plus +1` should not continue to output the same a11y error message, it should only output the a11y error message when the error message has changed (ie an additional error). I have already seen this a11y error message, it should not output it again - [and the code does suggest it should not be outputting the same message from last](https://github.com/vue-a11y/vue-axe/blob/master/src/utils.js#L17).

![image](https://user-images.githubusercontent.com/11144798/82885856-992e6f00-9f3d-11ea-8b0d-d262128a0e42.png)


When `clearConsoleOnUpdate === true`, it's clearing the console each time there is an update as you'd expect per the rule description.

Note this screenshot was taking very quickly before `vue-axe` cleared the console.
![image](https://user-images.githubusercontent.com/11144798/82886184-135ef380-9f3e-11ea-8b52-1e75bb465285.png)

But I'm not interested in having this rule turned on as now I can no longer see my console debug.

![image](https://user-images.githubusercontent.com/11144798/82886259-2ffb2b80-9f3e-11ea-905b-f6aaee43dd12.png)

Now each time I do an update with an a11y issue it'll clear the console before showing the a11y error message. Which is expected.

![image](https://user-images.githubusercontent.com/11144798/82886424-69cc3200-9f3e-11ea-8283-e5691d1a5620.png)

But this functionality is not what I want. I want to keep console debug, but I do not want repeated a11y error message being shown each time there is an update. I only need to see it once, and only display it again when there is an update to the a11y error messages.

**Comment by ktquez** [comment]
Yes, I understand now.
I will do some tests until the weekend and put it in a next version.

**Comment by ktquez** [comment]
@MechJosh0 

I made some internal changes, could you test [v2.2.2](https://github.com/vue-a11y/vue-axe/tree/v2.2.0)?

**Comment by MechJosh0** [comment]
Sorry for the slow response.

I've just got around to testing v2.3.1 and it's working as expected. Thank you 👍

**Comment by ktquez** [comment]
Thanks @MechJosh0
