### ISSUE TITLE
Console cleared even when `clearConsoleOnUpdate: false`

### ISSUE THREAD

**Issue by danielroe** [vue-a11y/vue-axe#28]
(Duplicate of https://github.com/vue-a11y/vue-axe/issues/26 - possible regression?)

When running `vue-axe` with the following options, the console is cleared on load and on subsequent updates.

```ts
Vue.use(VueAxe, {
  auto: true, // with or without this line
  clearConsoleOnUpdate: false,
})
```

**Comment by ktquez** [comment]
@danielroe Thank you for that.

I will do some tests and answer soon.

**Comment by darrinmn9** [comment]
I'm facing the same problem.

**Comment by ktquez** [comment]
Which version are you using?

The [demo](https://vue-axe.surge.sh/) is working as expected.

If it is with the most current version and the error is happening, could you reproduce it online?

**Comment by darrinmn9** [comment]
I can repro it on the demo link.

1. load the page, confirm you see output in the console
2. click on the "about" link, notice the console is cleared and you see 
```
Console was cleared                  vue-axe.js:25630
```

**Comment by ktquez** [comment]
@darrinmn9 
Clearing the console when changing routes is expected behavior.

https://github.com/vue-a11y/vue-axe/blob/master/src/index.js#L43

---

In this case, if there is a demand for such functionality, we can add another option of `clearConsoleOnRouteChange`

**Comment by darrinmn9** [comment]
Ah ok, im not sure if that is the same issue @danielroe is experiencing as well. 

In terms of adding another option, I think that naming it `clearConsoleOnRouteChange` is too specific. Some people just don't want any dependency clearing the console, especially during local development. so ideally there would be an option for "never clear the console"

**Comment by danielroe** [comment]
I would definitely want to disable clearing the console full stop as it clears lots of useful information I use in developing an app.

I initially filed this issue as on first load of a Nuxt app, the console is cleared. I will provide a repro.

**Comment by darrinmn9** [comment]
@ktquez @danielroe I created a PR to fix this, by adding an option `allowConsoleClears`. It defaults to `true` in order to not be a breaking change. Would love feedback.

https://github.com/vue-a11y/vue-axe/pull/30

**Comment by darrinmn9** [comment]
`allowConsoleClears` added in v2.4.0
