### ISSUE TITLE
Relax Peer Dependency on axe-core?

### ISSUE THREAD

**Issue by straub** [vue-a11y/vue-axe#31]
Hey folks,

Would it be acceptable to unpin the peer dependency on `axe-core`? It's causing npm warnings like
```
npm WARN vue-axe@2.4.0 requires a peer of axe-core@3.5.3 but none is installed. You must install peer dependencies yourself.
```
because I have axe-core@3.5.5.

It seems compatible. Was pinning this peer dependency possibly an oversight?

**Comment by ktquez** [comment]
Hello @Straub, sorry for the delay in responding.
I'm doing some tests with axe-core v4, I'm going to do some updates and fix it.

**Comment by straub** [comment]
Thanks!

Just to clarify, my warning is `3.5.3` vs. `3.5.5`, b/c the peer dependency here is pinned to a single version rather than a range, not necessarily due to v4, but that sounds great!

**Comment by straub** [comment]
The warning for `axe-core` 3.x went away in v2.4.1, thanks again!

**Comment by ktquez** [comment]
@straub 

I forgot to comment here 🤦‍♂️. 

I'm glad you saw it.

Thanks for your feedback. 🤘
