### ISSUE TITLE
Can't build due to type error. (Vue CLI)

### ISSUE THREAD

**Issue by lukewhrit** [vue-a11y/vue-axe#33]
There's an error logged by Vue when building in production mode that causes the application to exit and not build. This error only occurs when building in production.

There's no return value for the `customResultHandler` field in the `VueAxeOptions` interface. This is required by `tsc`.

![image](https://user-images.githubusercontent.com/38197656/96386956-e1f4f780-116c-11eb-9e35-4d20689b9683.png)

Since this fix is so easy I'll put a PR to fix it.

**Comment by ktquez** [comment]
Thanks @lukewhrit
