### ISSUE TITLE
Support for axe-core v4?

### ISSUE THREAD

**Issue by darrinmn9** [vue-a11y/vue-axe#35]
`axe-core` v4 has been out for a while. It doesnt seem like any of the breaking changes would affect the usage in this library (correct me if im wrong) https://github.com/dequelabs/axe-core/blob/develop/CHANGELOG.md#400-2020-07-28.

I do see this is updated in `vue-axe-next`. Would it be possible to update the peer dependency in the `vue-axe` v2 branch to allow users to use the newest version? Currently I believe the `peerDependencies` is locked into v3 (`"^3.5.3"`).

**Comment by ktquez** [comment]
That should do it, right?
```
"peerDependencies": {
  "axe-core": "3.x || 4.x"
}
```

**Comment by darrinmn9** [comment]
yup, looks like the correct syntax to me!

**Comment by ktquez** [comment]
Done! [v2.4.3](https://github.com/vue-a11y/vue-axe/tree/v2.4.3)

Thanks @darrinmn9
