### ISSUE TITLE
TypeScript definitions?

### ISSUE THREAD

**Issue by tylucaskelley** [vue-a11y/vue-axe#5]
Noticed that there are no TypeScript definition files or an `@types/vue-axe` module available to use - would be nice to have those definitions available here for projects using TypeScript.

**Comment by ktquez** [comment]
Hello @tylucaskelley , how are you? This issue has gone unnoticed by me, forgive me.

I do not have much experience with TypeScript, so we accept pull requests.

Thank you for using

**Comment by ktquez** [comment]
@tylucaskelley 

Now available in this [v1.2.0](https://github.com/vue-a11y/vue-axe#configuration).
We added some typescript definitions in the index.d.ts file, could you check with this new version?
If you find any correction, feel free to send us a PR, we will be grateful.

Thanks for the suggestion.
